from typing import Protocol
from uuid import UUID
from .schemas import AnalysisJob, CreateAnalysisJob, CreateReview

class AnalysisJobRepository(Protocol):
    async def create(self, command: CreateAnalysisJob) -> AnalysisJob: ...
    async def get(self, job_id: UUID) -> AnalysisJob | None: ...
class ReviewRepository(Protocol):
    async def create(self, decision_id: UUID, command: CreateReview, reviewer_id: UUID) -> UUID: ...
class EventPublisher(Protocol):
    async def publish_outbox(self, name: str, payload: dict) -> None: ...
