"""OpenAPI contract smoke test.

This is a small but important test: it verifies that the OpenAPI schema
generated by the app is valid and contains all expected endpoints.
A regression in router wiring would surface here.
"""
from __future__ import annotations

import os
import unittest

os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")
os.environ.setdefault("JWT_SECRET", "test-secret-for-unit-tests-only")


EXPECTED_PATHS = {
    # Auth
    "/v1/auth/login",
    "/v1/auth/refresh",
    "/v1/auth/me",
    # Assets
    "/v1/assets",
    "/v1/assets/{asset_id}",
    "/v1/assets/{asset_id}/downloadUrl",
    "/v1/assets:prepareUpload",
    "/v1/assets/{asset_id}:completeUpload",
    "/v1/assets/{asset_id}:createClips",
    "/v1/assets:importFromUrl",
    # Jobs
    "/v1/analysis-jobs",
    "/v1/analysis-jobs/{job_id}",
    "/v1/analysis-jobs/{job_id}/artifacts",
    "/v1/analysis-jobs/{job_id}:cancel",
    "/v1/analysis-jobs/{job_id}:retry",
    # Subjects
    "/v1/subjects",
    "/v1/subjects/{subject_id}",
    "/v1/subjects/{subject_id}/consent",
    # Words
    "/v1/words",
    "/v1/words/{word}/templates",
    "/v1/words/{word}/templates/{template_id}",
    "/v1/words/{word}/samples",
    "/v1/words/{word}/samples/{sample_id}/urls",
    # Reviews
    "/v1/reviews",
    "/v1/reviews/{review_id}",
    # Models
    "/v1/models",
    "/v1/models/{model_id}",
    "/v1/models/{model_id}:promote",
    # Audit
    "/v1/audit",
    "/v1/audit/export",
    # Dashboard
    "/v1/dashboard/metrics",
    # System
    "/health/live",
    "/health/ready",
    "/metrics",
    "/info",
}


class OpenAPIContractTests(unittest.TestCase):
    def test_all_expected_endpoints_present(self):
        from app.main import app

        schema = app.openapi()
        paths = set(schema.get("paths", {}).keys())
        missing = EXPECTED_PATHS - paths
        self.assertEqual(missing, set(), f"Missing endpoints: {sorted(missing)}")

    def test_no_unexpected_endpoints(self):
        """Detect routes added without updating EXPECTED_PATHS."""
        from app.main import app

        schema = app.openapi()
        paths = set(schema.get("paths", {}).keys())
        unexpected = paths - EXPECTED_PATHS
        # Allow 5% drift as scaffolding is added
        self.assertLessEqual(
            len(unexpected),
            max(2, len(EXPECTED_PATHS) // 20),
            f"Unexpected endpoints (update EXPECTED_PATHS): {sorted(unexpected)}",
        )

    def test_all_endpoints_have_operation_id(self):
        from app.main import app

        schema = app.openapi()
        for path, methods in schema["paths"].items():
            for method, op in methods.items():
                if method in ("parameters", "get", "post", "put", "patch", "delete"):
                    self.assertIn(
                        "operationId",
                        op,
                        f"{method.upper()} {path} has no operationId",
                    )

    def test_no_500_default_response_only(self):
        """Every endpoint must define at least one success response."""
        from app.main import app

        schema = app.openapi()
        for path, methods in schema["paths"].items():
            for method, op in methods.items():
                if method in ("parameters",):
                    continue
                responses = op.get("responses", {})
                success_codes = [
                    code for code in responses if code.startswith("2") and code != "204"
                ]
                if not success_codes:
                    # 204 is allowed (No Content)
                    if "204" in responses:
                        continue
                    self.fail(f"{method.upper()} {path} has no 2xx response")
